export const searchSnippet = [
  "Node* search(Node* root, int key) {",
  "    if (root == NULL || root->data == key)",
  "        return root;",
  "    if (key < root->data)",
  "        return search(root->left, key);",
  "    else",
  "        return search(root->right, key);",
  "}",
];

export const insertSnippet = [
  "Node* insert(Node* root, int key) {",
  "    if (root == NULL)",
  "        return new Node(key);",
  "    if (key < root->data)",
  "        root->left = insert(root->left, key);",
  "    else if (key > root->data)",
  "        root->right = insert(root->right, key);",
  "    return root;",
  "}",
];

export const iterativeInsertWithParentSnippet = [
  "Node* insert(Node* root, int key) {",
  "    Node* parent = NULL;",
  "    Node* curr = root;",
  "    while (curr != NULL) {",
  "        parent = curr;",
  "        if (key < curr->data)",
  "            curr = curr->left;",
  "        else if (key > curr->data)",
  "            curr = curr->right;",
  "        else",
  "            return root;",
  "    }",
  "    Node* node = new Node(key);",
  "    if (parent == NULL) return node;",
  "    if (key < parent->data) parent->left = node;",
  "    else parent->right = node;",
  "    return root;",
  "}",
];

export const removalSnippet = [
  "Node* deleteNode(Node* root, int key) {",
  "    if (root == NULL)",
  "        return NULL;",
  "    if (key < root->data)",
  "        root->left = deleteNode(root->left, key);",
  "    else if (key > root->data)",
  "        root->right = deleteNode(root->right, key);",
  "    else {",
  "        if (root->left == NULL)",
  "            return root->right;",
  "        if (root->right == NULL)",
  "            return root->left;",
  "        Node* succ = minValueNode(root->right);",
  "        root->data = succ->data;",
  "        root->right = deleteNode(root->right, succ->data);",
  "    }",
  "    return root;",
  "}",
];

export const removalWithParentSnippet = [
  "Node* deleteNode(Node* root, int key) {",
  "    Node* parent = NULL;",
  "    Node* curr = root;",
  "    while (curr && curr->data != key) {",
  "        parent = curr;",
  "        if (key < curr->data) curr = curr->left;",
  "        else curr = curr->right;",
  "    }",
  "    if (!curr) return root;",
  "    if (curr->left == NULL || curr->right == NULL) {",
  "        Node* child = curr->left ? curr->left : curr->right;",
  "        if (!parent) root = child;",
  "        else if (parent->left == curr) parent->left = child;",
  "        else parent->right = child;",
  "    } else {",
  "        Node* succParent = curr;",
  "        Node* succ = curr->right;",
  "        while (succ->left) {",
  "            succParent = succ;",
  "            succ = succ->left;",
  "        }",
  "        curr->data = succ->data;",
  "        if (succParent->left == succ) succParent->left = succ->right;",
  "        else succParent->right = succ->right;",
  "    }",
  "    return root;",
  "}",
];

export const traversalSnippet = [
  "void inorder(Node* root) {",
  "    if (root == NULL) return;",
  "    inorder(root->left);",
  "    visit(root);",
  "    inorder(root->right);",
  "}",
  "",
  "void preorder(Node* root) {",
  "    if (root == NULL) return;",
  "    visit(root);",
  "    preorder(root->left);",
  "    preorder(root->right);",
  "}",
  "",
  "void postorder(Node* root) {",
  "    if (root == NULL) return;",
  "    postorder(root->left);",
  "    postorder(root->right);",
  "    visit(root);",
  "}",
  "",
  "void levelorder(Node* root) {",
  "    queue<Node*> q;",
  "    q.push(root);",
  "    while (!q.empty()) {",
  "        Node* node = q.front(); q.pop();",
  "        visit(node);",
  "        if (node->left) q.push(node->left);",
  "        if (node->right) q.push(node->right);",
  "    }",
  "}",
];

export const heightSnippet = [
  "int height(Node* root) {",
  "    if (root == NULL)",
  "        return -1;",
  "    int left = height(root->left);",
  "    int right = height(root->right);",
  "    return 1 + max(left, right);",
  "}",
];

export const parentOpsSnippet = [
  ...iterativeInsertWithParentSnippet,
  "",
  ...removalWithParentSnippet,
];
