// src/codeSnippets.js
export const mergeSortCode = [
  `<span class="kw">void</span> merge(<span class="type">vector</span>&lt;<span class="type">int</span>&gt;& arr, <span class="type">int</span> left, <span class="type">int</span> mid, <span class="type">int</span> right) {`,
  `  <span class="type">int</span> n1 = mid - left + 1;`,
  `  <span class="type">int</span> n2 = right - mid;`,
  `  <span class="type">vector</span>&lt;<span class="type">int</span>&gt; leftArr(n1), rightArr(n2);`,
  `  <span class="kw">for</span> (<span class="type">int</span> i = 0; i &lt; n1; ++i) {`,
  `    leftArr[i] = arr[left + i];`,
  `  }`,
  `  <span class="kw">for</span> (<span class="type">int</span> j = 0; j &lt; n2; ++j) {`,
  `    rightArr[j] = arr[mid + 1 + j];`,
  `  }`,
  `  <span class="type">int</span> i = 0, j = 0, k = left;`,
  `  <span class="kw">while</span> (i &lt; n1 && j &lt; n2) {`,
  `    <span class="kw">if</span> (leftArr[i] <= rightArr[j]) {`,
  `      arr[k++] = leftArr[i++];`,
  `    } <span class="kw">else</span> {`,
  `      arr[k++] = rightArr[j++];`,
  `    }`,
  `  }`,
  `  <span class="kw">while</span> (i &lt; n1) {`,
  `    arr[k++] = leftArr[i++];`,
  `  }`,
  `  <span class="kw">while</span> (j &lt; n2) {`,
  `    arr[k++] = rightArr[j++];`,
  `  }`,
  `}`,
  ``,
  `<span class="kw">void</span> mergeSort(<span class="type">vector</span>&lt;<span class="type">int</span>&gt;& arr, <span class="type">int</span> left, <span class="type">int</span> right) {`,
  `  <span class="kw">if</span> (left >= right) {`,
  `    <span class="kw">return</span>;`,
  `  }`,
  `  <span class="type">int</span> mid = left + (right - left) / 2;`,
  `  mergeSort(arr, left, mid);`,
  `  mergeSort(arr, mid + 1, right);`,
  `  merge(arr, left, mid, right);`,
  `}`,
  ``,
  `<span class="type">int</span> main() {`,
  `  <span class="type">vector</span>&lt;<span class="type">int</span>&gt; arr;`,
  `  mergeSort(arr, 0, arr.size() - 1);`,
  `  <span class="kw">return</span> 0;`,
  `}`
];
