export const codeSnippets = {
  append: [
    "void ListAppend(List& list, int value) {",
    "  ListNode* newNode = new ListNode(value);",
    "  if (list.head == nullptr) {",
    "    list.head = newNode;",
    "    list.tail = newNode;",
    "    return;",
    "  }",
    "  ListNode* cur = list.head;",
    "  while (cur->next != nullptr) {",
    "    cur = cur->next;",
    "  }",
    "  cur->next = newNode;",
    "  newNode->prev = cur;",
    "  list.tail = newNode;",
    "}",
  ],
  prepend: [
    "void ListPrepend(List& list, int value) {",
    "  ListNode* newNode = new ListNode(value);",
    "  newNode->next = list.head;",
    "  if (list.head != nullptr) {",
    "    list.head->prev = newNode;",
    "  }",
    "  list.head = newNode;",
    "  if (list.tail == nullptr) {",
    "    list.tail = newNode;",
    "  }",
    "}",
  ],
  insertAfter: [
    "void ListInsertNodeAfter(List& list, int targetValue, int value) {",
    "  ListNode* target = list.head;",
    "  while (target != nullptr && target->data != targetValue) {",
    "    target = target->next;",
    "  }",
    "  if (target == nullptr) return;",
    "  ListNode* newNode = new ListNode(value);",
    "  newNode->next = target->next;",
    "  newNode->prev = target;",
    "  if (target->next != nullptr) {",
    "    target->next->prev = newNode;",
    "  } else {",
    "    list.tail = newNode;",
    "  }",
    "  target->next = newNode;",
    "}",
  ],
  removeAfter: [
    "void ListRemoveNodeAfter(List& list, int targetValue) {",
    "  ListNode* target = list.head;",
    "  while (target != nullptr && target->data != targetValue) {",
    "    target = target->next;",
    "  }",
    "  if (target == nullptr || target->next == nullptr) return;",
    "  ListNode* removed = target->next;",
    "  target->next = removed->next;",
    "  if (removed->next != nullptr) {",
    "    removed->next->prev = target;",
    "  } else {",
    "    list.tail = target;",
    "  }",
    "  delete removed;",
    "}",
  ],
  removeByValue: [
    "void ListRemoveByValue(List& list, int value) {",
    "  if (list.head == nullptr) return;",
    "  if (list.head->data == value) {",
    "    ListNode* removed = list.head;",
    "    list.head = removed->next;",
    "    if (list.head != nullptr) list.head->prev = nullptr;",
    "    if (list.tail == removed) list.tail = list.head;",
    "    delete removed;",
    "    return;",
    "  }",
    "  ListNode* prev = list.head;",
    "  ListNode* cur = list.head->next;",
    "  while (cur != nullptr && cur->data != value) {",
    "    prev = cur;",
    "    cur = cur->next;",
    "  }",
    "  if (cur == nullptr) return;",
    "  prev->next = cur->next;",
    "  if (cur->next != nullptr) cur->next->prev = prev;",
    "  if (list.tail == cur) list.tail = prev;",
    "  delete cur;",
    "}",
  ],
  traverse: [
    "void ListTraversal(const List& list) {",
    "  ListNode* cur = list.head;",
    "  while (cur != nullptr) {",
    "    Visit(cur->data);",
    "    cur = cur->next;",
    "  }",
    "}",
  ],
};
