export const codeSnippets = {
  dll: [
    "void ListInsertionSortDoublyLinked(List& list) {",
    "  ListNode* curNode = list.head != nullptr ? list.head->next : nullptr;",
    "  while (curNode != nullptr) {",
    "    ListNode* nextNode = curNode->next;",
    "    ListNode* searchNode = curNode->prev;",
    "    while (searchNode != nullptr && searchNode->data > curNode->data) {",
    "      searchNode = searchNode->prev;",
    "    }",
    "    ListRemoveNode(list, curNode);",
    "    if (searchNode == nullptr) {",
    "      curNode->prev = nullptr;",
    "      ListPrependNode(list, curNode);",
    "    } else {",
    "      ListInsertNodeAfter(list, searchNode, curNode);",
    "    }",
    "    curNode = nextNode;",
    "  }",
    "}",
  ],
  sll: [
    "void ListInsertionSortSinglyLinked(List& list) {",
    "  if (list.head == nullptr) return;",
    "  ListNode* sortedTail = list.head;",
    "  ListNode* curNode = sortedTail->next;",
    "  while (curNode != nullptr) {",
    "    if (curNode->data >= sortedTail->data) {",
    "      sortedTail = curNode;",
    "      curNode = curNode->next;",
    "    } else {",
    "      sortedTail->next = curNode->next;",
    "      if (curNode->data < list.head->data) {",
    "        curNode->next = list.head;",
    "        list.head = curNode;",
    "      } else {",
    "        ListNode* search = list.head;",
    "        while (search->next != nullptr && search->next->data < curNode->data) {",
    "          search = search->next;",
    "        }",
    "        curNode->next = search->next;",
    "        search->next = curNode;",
    "      }",
    "      curNode = sortedTail->next;",
    "    }",
    "  }",
    "}",
  ],
};
