export const traversalSnippets = {
  bfs: [
    "void bfs(const Graph& g, int start) {",
    "  queue<int> q;",
    "  vector<bool> visited(g.size(), false);",
    "  visited[start] = true;",
    "  q.enquque(start);",
    "",
    "  while (!q.empty()) {",
    "    int u = q.front();",
    "    q.dequeue();",
    "",
    "    for (int v : g.adj[u]) {",
    "      if (visited[v]) continue;",
    "      visited[v] = true;",
    "      q.enquque(v);",
    "    }",
    "  }",
    "}",
  ],
  dfsStack: [
    "void dfsIterative(const Graph& g, int start) {",
    "  stack<int> st;",
    "  vector<bool> visited(g.size(), false);",
    "  st.push(start);",
    "",
    "  while (!st.empty()) {",
    "    int u = st.top();",
    "    st.pop();",
    "    if (visited[u]){",
    "      continue;",
    "    }",
    "    visited[u] = true;",
    "",
    "    for (int v : g.adj[u]) {",
    "      if (!visited[v]){",
    "        st.push(v);",
    "      }",
    "    }",
    "  }",
    "}",
  ],
  dfsRecursive: [
    "void dfsRecursive(const Graph& g, int u, vector<bool>& visited) {",
    "  visited[u] = true;",
    "",
    "  for (int v : g.adj[u]) {",
    "    if (visited[v]) continue;",
    "    dfsRecursive(g, v, visited);",
    "  }",
    "}",
    "",
    "void dfs(const Graph& g, int start) {",
    "  vector<bool> visited(g.size(), false);",
    "  dfsRecursive(g, start, visited);",
    "}",
  ],
  dijkstra: [
    "vector<int> dijkstra(const Graph& g, int start) {",
    "  const int INF = 1e9;",
    "  //shortest path from start to vertex",
    "  vector<int> dist(g.size(), INF);",
    "  //parent[u] the predecessor of u",
    "  vector<int> parent(g.size(), -1);",
    "  //alias for the heap element (curr_dist, vertex)",
    "  using State = pair<int,int>;",
    "  priority_queue<State, vector<State>, greater<State>> pq;//min heap",
    "  dist[start] = 0;",
    "  pq.push({0, start});",
    "",
    "  while (!pq.empty()) {",
    "    auto [d, u] = pq.top();",
    "    pq.pop();",
    "    //skip if this heap entry is stale",
    "    if (d != dist[u]) continue;",
    "    for (auto [v, w] : g.adj[u]) {",
    "      //if path from u to v does not improve disk[v], skip",
    "      if (dist[v] <= dist[u] + w) continue;",
    "      //otherwise, update the shorter distance",
    "      dist[v] = dist[u] + w;",
    "      parent[v] = u;",
    "      // push the imporved state for v into the heal",
    "      pq.push({dist[v], v});",
    "    }",
    "  }",
    "",
    "  return dist;",
    "}",
  ],
};
