// src/codeSnippets.js
export const quickSortCode = [
  "<span class=\"type\">int</span> partition(<span class=\"type\">int</span> arr[], <span class=\"type\">int</span> low, <span class=\"type\">int</span> high) {",
  "    <span class=\"type\">int</span> midpoint = low + (high - low) / 2;",
  "    <span class=\"type\">int</span> pivot = arr[midpoint];",
  "    <span class=\"type\">int</span> i = low, j = high;",
  "    <span class=\"kw\">while</span> (i <= j) {",
  "        <span class=\"kw\">while</span> (arr[i] &lt; pivot)",
  "            i += 1;",
  "        <span class=\"kw\">while</span> (arr[j] &gt; pivot)",
  "            j -= 1;",
  "        <span class=\"kw\">if</span> (i >= j) <span class=\"kw\">break</span>;",
  "        <span class=\"standard\">std</span>::<span class=\"func\">swap</span>(arr[i], arr[j]);",
  "        i += 1;",
  "        j -= 1;",
  "    }",
  "    <span class=\"kw\">return</span> j;",
  "}",
  "",
  "<span class=\"kw\">void</span> quicksort(<span class=\"type\">int</span> arr[], <span class=\"type\">int</span> low, <span class=\"type\">int</span> high) {",
  "    <span class=\"kw\">if</span> (low >= high) <span class=\"kw\">return</span>;",
  "    <span class=\"type\">int</span> p = partition(arr, low, high);",
  "    quicksort(arr, low, p);",
  "    quicksort(arr, p + 1, high);",
  "}",
  "",
  "<span class=\"type\">int</span> main() {",
  "    <span class=\"type\">int</span> arr[];",
  "    <span class=\"type\">int</span> n = sizeof(arr) / sizeof(arr[0]);",
  "    quicksort(arr, 0, n - 1);",
  "    <span class=\"kw\">return</span> 0;",
  "}"
];
