export const radixCode = [
  "void radixSort(int arr[], int n) {",
  "  vector<int> buckets[10];",
  "  int maxDigits = getMaxDigits(arr, n);",
  "  int place = 1;",
  "  for (int d = 0; d < maxDigits; d++) {",
  "    for (int i = 0; i < n; i++) {",
  "      int digit = abs(arr[i] / place) % 10;",
  "      buckets[digit].push_back(arr[i]);",
  "    }",
  "    int idx = 0;",
  "    for (int i = 0; i < 10; i++) {",
  "      for (int j = 0; j < buckets[i].size(); j++) {",
  "        arr[idx++] = buckets[i][j];",
  "      }",
  "      buckets[i].clear();",
  "    }",
  "    place *= 10;",
  "  }",
  "  vector<int> negatives, nonNegatives;",
  "  for (int i = 0; i < n; i++) {",
  "    if (arr[i] < 0) negatives.push_back(arr[i]);",
  "    else nonNegatives.push_back(arr[i]);",
  "  }",
  "  reverse(negatives.begin(), negatives.end());",
  "  int idx = 0;",
  "  for (int i = 0; i < negatives.size(); i++){",
  "    arr[idx++] = negatives[i];}",
  "  for (int i = 0; i < nonNegatives.size(); i++){",
  "    arr[idx++] = nonNegatives[i];}",
  "}",
  "int getMaxDigits(int arr[], int n) {",
  "  int maxVal = 0;",
  "  for (int i = 0; i < n; i++) {",
  "    if (abs(arr[i]) > maxVal) maxVal = abs(arr[i]);",
  "  }",
  "  int digits = 0;",
  "  while (maxVal > 0) {",
  "    digits++;",
  "    maxVal /= 10;",
  "  }",
  "  return digits;",
  "}",
];
